-- Tabela de endereços
CREATE TABLE ENDERECO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO VARCHAR(255) NOT NULL
);

-- Tabela de clientes
CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO_ID INT NOT NULL,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);

-- Tabela de produtos
CREATE TABLE PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) ,
    VALOR DECIMAL(10,2)
);

-- Tabela de pedidos
CREATE TABLE PEDIDO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    VALOR DECIMAL(10,2),
    ENDERECO_ID INT,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);

-- Tabela de Pedido e Produto
CREATE TABLE PRODUTO_PEDIDO (
    PEDIDO_ID INT NOT NULL,
    PRODUTO_ID INT NOT NULL,
    PRIMARY KEY (PEDIDO_ID, PRODUTO_ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);

-- Tabela de Entrega
CREATE TABLE ENTREGA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO_ID INT,
    PEDIDO_ID INT,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID)
);
